// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "OnePlus";    // Network SSID (name)
const char PASS[]     = "ab2kcauq";    // Network password (use for WPA, or use as key for WEP)

void onButtonPressedChange();
void onFeedNowChange();

String statusMessage;
bool buttonPressed;
bool feedNow;

void initProperties(){

  ArduinoCloud.addProperty(statusMessage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(buttonPressed, READWRITE, ON_CHANGE, onButtonPressedChange);
  ArduinoCloud.addProperty(feedNow, READWRITE, ON_CHANGE, onFeedNowChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
